spring:
  datasource:
    url: jdbc:h2:mem:travelbuddy
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.web: INFO
    com.travelbuddy: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info


